### ISSUE TITLE
Document JS cgl

### ISSUE THREAD

**Issue by tmotyl** [TYPO3-Documentation/TYPO3CMS-Reference-CodingGuidelines#15]
TYPO3 Core team has decided to follow Airbnb CGL rules for JS files.
https://decisions.typo3.org/t/results-define-coding-guidelines-for-javascript/301

In this document we should at last:
- refer to airbnb rule set
- highlight few most important like:
-- 2 spaces indentation (no TABS)
-- single quotes should be used
--  jQuery variable should start with $
-- space between function keyword and opening bracket like `function () {`

**Comment by liayn** [comment]
Please be cautious about the distinction between brackets, parentheses and braces in US English. I would in this case use parentheses or emphasize “round brackets“.

**Comment by tmotyl** [comment]
@liayn thanks for pointing it out. Until now I used  "parentheses" "brackets" as synonyms, but you're totally right that they mean different things.

**Comment by Chrissitopher** [comment]
This issue was moved to TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#218
